### ISSUE TITLE
Runtime Platform missing or download incomplete (umu related issue)

### ISSUE THREAD

**Issue by goluboch** [NelloKudo/osu-winello#106]
Tried installing with this script three times, osu-wine errors out even after relaunching the terminal. Only thing I've changed during the install is osu's game path.
```
/m/s/r/osu-winello>./osu-wine
ERROR: _v2-entry-point (umu) cannot be found in '/home/golub/.local/share/umu'
Runtime Platform missing or download incomplete
Traceback (most recent call last):
  File "/home/golub/.local/share/osuconfig/proton-osu/umu-run/__main__.py", line 14, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/golub/.local/share/osuconfig/proton-osu/umu-run/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/home/golub/.local/share/osuconfig/proton-osu/umu-run/umu/umu_run.py", line 844, in main
    command: tuple[Path | str, ...] = build_command(env, UMU_LOCAL, opts)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/golub/.local/share/osuconfig/proton-osu/umu-run/umu/umu_run.py", line 368, in build_command
    raise FileNotFoundError(err)
FileNotFoundError: _v2-entry-point (umu) cannot be found in '/home/golub/.local/share/umu'
Runtime Platform missing or download incomplete
```

**Comment by goluboch** [comment]
> Can you try changing [this line](https://github.com/NelloKudo/osu-winello/blob/2f1722db479d99a55ff1f909081c78252a50b9c6/osu-wine#L14) in your `~/.local/bin/osu-wine` to =1?

Outputs the same error.

The _v2-entry-point is in `~/.local/share/umu` though, despite the error saying it's not.

**Comment by goluboch** [comment]
> The bundled `umu-run` is a bit outdated, can you try replacing your `/home/golub/.local/share/osuconfig/proton-osu/umu-run` file with the latest version from here? https://github.com/Open-Wine-Components/umu-launcher/actions/runs/11421625495

That outputs the same error again, but now providing info about umu-launcher's version and stating that steamrt is up to date.

**Comment by goluboch** [comment]
> Can you send the log from `UMU_LOG=debug osu-wine`?

[umulog.log](https://github.com/user-attachments/files/17450311/umulog.log)

**Comment by goluboch** [comment]
> Thanks. Although nothing really stands out in the log, have you tried completely removing the `~/.local/share/umu` yet? It could be corrupted in some way.

Thank you, that fixed the issue! Seems like the install was somehow corrupt, sorry. osu runs fine. However, it's still weird how it didn't redownload the folder when I reinstalled the game.
