### ISSUE TITLE
Can't run AIMod

### ISSUE THREAD

**Issue by 64ArthurAraujo** [NelloKudo/osu-winello#66]
Looking at the runtime.log it seems to be a font issue?

```
...
2024-03-21T07:28:02: ERROR: soft handled
2024-03-21T07:28:02: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Font 'Microsoft YaHei UI' does not support style 'Regular'.
2024-03-21T07:28:02: at System.Drawing.Font.CreateNativeFont()
2024-03-21T07:28:02: at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
2024-03-21T07:28:02: at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
2024-03-21T07:28:02: at System.Drawing.Font..ctor(String familyName, Single emSize)
2024-03-21T07:28:02: at #=zoK9RmJrg77IgUYugT9RafJ$iLrpm6LYKQ9uugtM=.#=zQJKpSiVG1u$v()
2024-03-21T07:28:02: at #=zoK9RmJrg77IgUYugT9RafJ$iLrpm6LYKQ9uugtM=..ctor(#=zVNEIXbeXTXPPenUV87woFjmU2SKW #=z45fvA2k=)
2024-03-21T07:28:02: at #=zVNEIXbeXTXPPenUV87woFjmU2SKW.#=zhaWNkdUwLq$h()
2024-03-21T07:28:02: at #=zVNEIXbeXTXPPenUV87woFjmU2SKW.#=zjUHZ5iZMf_pgbXmW1Q==(Object #=zGMAdaLU=, Keys #=zqeXt9Sg=, Boolean #=zps_lTKU=)
2024-03-21T07:28:02: --- End of inner exception stack trace ---
2024-03-21T07:28:02: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2024-03-21T07:28:02: at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2024-03-21T07:28:02: at System.Delegate.DynamicInvokeImpl(Object[] args)
2024-03-21T07:28:02: at #=zFFa5Be4TTxJHJRmmu47_w4w=.#=ztAEAZ_5JnSER(Keys #=zqeXt9Sg=, Boolean #=zps_lTKU=)
2024-03-21T07:28:02: at #=zFFa5Be4TTxJHJRmmu47_w4w=.#=zm1VstkFTzC1W(Keys #=zqeXt9Sg=)
2024-03-21T07:28:02: at #=z0_XJIXhmCRsNNe0PuQ==.#=zrEqKn7o=(List`1 #=zcRm$CBg=)
2024-03-21T07:28:02: at #=z0_XJIXhmCRsNNe0PuQ==.#=zib5_4mA=(#=zxVEbENJoVyyTFEGjOdcb3Xg= #=zG5t1qVw=)
2024-03-21T07:28:02: at #=zduF3QmjgMG4eSc$fOQ==.#=zCU0pfvw=()
2024-03-21T07:28:02: ERROR:
2024-03-21T07:28:02: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Font 'Microsoft YaHei UI' does not support style 'Regular'.
2024-03-21T07:28:02: at System.Drawing.Font.CreateNativeFont()
2024-03-21T07:28:02: at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
2024-03-21T07:28:02: at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
2024-03-21T07:28:02: at System.Drawing.Font..ctor(String familyName, Single emSize)
2024-03-21T07:28:02: at #=zoK9RmJrg77IgUYugT9RafJ$iLrpm6LYKQ9uugtM=.#=zQJKpSiVG1u$v()
2024-03-21T07:28:02: at #=zoK9RmJrg77IgUYugT9RafJ$iLrpm6LYKQ9uugtM=..ctor(#=zVNEIXbeXTXPPenUV87woFjmU2SKW #=z45fvA2k=)
2024-03-21T07:28:02: at #=zVNEIXbeXTXPPenUV87woFjmU2SKW.#=zhaWNkdUwLq$h()
2024-03-21T07:28:02: at #=zVNEIXbeXTXPPenUV87woFjmU2SKW.#=zjUHZ5iZMf_pgbXmW1Q==(Object #=zGMAdaLU=, Keys #=zqeXt9Sg=, Boolean #=zps_lTKU=)
2024-03-21T07:28:02: --- End of inner exception stack trace ---
2024-03-21T07:28:02: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2024-03-21T07:28:02: at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2024-03-21T07:28:02: at System.Delegate.DynamicInvokeImpl(Object[] args)
2024-03-21T07:28:02: at #=zFFa5Be4TTxJHJRmmu47_w4w=.#=ztAEAZ_5JnSER(Keys #=zqeXt9Sg=, Boolean #=zps_lTKU=)
2024-03-21T07:28:02: at #=zFFa5Be4TTxJHJRmmu47_w4w=.#=zm1VstkFTzC1W(Keys #=zqeXt9Sg=)
2024-03-21T07:28:02: at #=z0_XJIXhmCRsNNe0PuQ==.#=zrEqKn7o=(List`1 #=zcRm$CBg=)
2024-03-21T07:28:02: at #=z0_XJIXhmCRsNNe0PuQ==.#=zib5_4mA=(#=zxVEbENJoVyyTFEGjOdcb3Xg= #=zG5t1qVw=)
2024-03-21T07:28:02: at #=zduF3QmjgMG4eSc$fOQ==.#=zCU0pfvw=()
```

**Comment by NelloKudo** [comment]
Never tried running it before but make sure you’re on the same Wine and Wineprefix as osu! and try again (?)

```
export PATH=~/.local/share/osuconfig/wine-osu/bin:$PATH
export WINEPREFIX=~/.local/share/wineprefixes/osu-wineprefix
wine aimod.exe

**Comment by 64ArthurAraujo** [comment]
Ran:
```
arthur@fedora:~/.local/share/osu-wine/osu!$ osu-wine --info

Winello: Need info?:
    Wineprefix location: /home/arthur/.local/share/wineprefixes/osu-wineprefix
    osu! folder: '/home/arthur/.local/share/osu-wine/osu!'

    If you need to add more options to osu!, see around line 68 of the script (ex. nano ~/.local/bin/osu-wine)
    You can run 'osu-wine --help' to see all the script's functions (fix prefix, w10 fonts etc.)
    You can find more troubleshooting and info at here: https://osu.ppy.sh/community/forums/topics/1248084?n=1

arthur@fedora:~/.local/share/osu-wine/osu!$ export PATH=~/.local/share/osuconfig/wine-osu/bin:$PATH

arthur@fedora:~/.local/share/osu-wine/osu!$ which wine
~/.local/share/osuconfig/wine-osu/bin/wine

arthur@fedora:~/.local/share/osu-wine/osu!$ export WINEPREFIX=~/.local/share/wineprefixes/osu-wineprefix/

arthur@fedora:~/.local/share/osu-wine/osu!$ wine ./osu\!.exe 
```

Same problem

**Comment by NelloKudo** [comment]
![image](https://github.com/NelloKudo/osu-winello/assets/98063377/e0f6299c-6a5f-42f1-9853-0850ee4ce952)

Got it working, it really is a missing font issue apparently. Really sucks to see how it was hardcoded to expect *that* font but it's stable after all xd
Pushing an update later to actually make it easier to fix!

**Comment by 64ArthurAraujo** [comment]
working here, thanks
